### ISSUE TITLE
NPE in client overlay

### ISSUE THREAD

**Issue by kreezxil** [AustereTony-MCMods/Oxygen-Core#5]
I have a few of your mods in my new Bane of Dragons modpack available on CurseForge and Twitch Launcher and one my players received the following crash report in their client.

I don't know what they were doing to trigger it and the stack trace is unclear as to which of your mods is the issue, therefore I am assuming the core for no other reason than that.

https://pastebin.com/pu9daWL0

We're using:

**Mod** | **Version**
--------- | ----------
Oxygen Core | 1.12.2-0.8.2
Oxygen Exchange | 1.12.2-0.8.0
Oxygen Friends List | 1.12.2-0.8.1
Oxygen Groups | 1.12.2-0.8.2
Oxygen Interaction | 1.12.2-0.8.1
Oxygen Mail | 1.12.2-0.8.1
Oxygen Menu | 1.12.2-0.8.0
Oxygen Players List | 1.12.2-0.8.1

**Comment by Drakyl** [comment]
Was just killing zombies when it crashed. Hacking with a sword the old school way. I should add rebooting the game seemed to solve it.

**Comment by AustereTony-MCMods** [comment]
Hello. I'm sorry, but I can’t release patches at the moment. I will eliminate the possibility of this error appearing only in the next major update (0.9b). Hope for understanding. Thanks for the report.

**Comment by kreezxil** [comment]
I don't know what your update cycle is? Please enlighten me.

**Comment by AustereTony-MCMods** [comment]
This is my first major project and due to the large number of modules and dependencies on the general API, updates are divided into two types - patches and updates of the API. Patches contain new features and fixes. API updates occur with the release of a new module and fundamental changes. I can’t release patches in the process of updating the API. Timing is pretty hard to predict.

Now in the process of development, the largest update, as well as a new module - a trading platform for players (Trade). The 0.9 release is due to take place this week (Core, Mail, Trade and Menu). The remaining modules will be updated within a couple of weeks.

Thank you for using my project. I hope in the future there will be more benefit from it.

**Comment by AustereTony-MCMods** [comment]
Hello.
The problem should be fixed, update 0.9 is almost complete. Groups and Friends List will be available next week.

**Comment by AustereTony-MCMods** [comment]
Consider it closed.
